variable "region" {}
variable "accountId" {}
variable "PAGE_ACCESS_TOKEN" {}
variable "CHALLENGE_SECRET" {}
variable "DYNAMO_SONGS_IN_FLIGHT_TABLE_NAME" {}
variable "DYNAMO_USERS_TABLE_NAME" {}
variable "SPOTIFY_CLIENT_ID" {}
variable "SPOTIFY_CLIENT_SECRET" {}
variable "USERS_NAME_INDEX" {}
